config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  root :to => "movies#index"
  resources :movies

  resources :reviews
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :users, through: :reviews
  
  validates :movie_url, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :movies, through: :reviews       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protected

  def after_sign_in_path_for(resource)
    reviews_path
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @movies = Movie.all
  end  

  def show
    @movie = Movie.find_by(id: params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    
  private
  def sign_up_params 
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_user, only: [:edit, :update, :destroy]
  before_action :check_movie_url, only: :create

  def index
    @reviews = current_user.reviews
  end

  def new
    @review = current_user.reviews.new
  end

  def edit
  end

  def create
    if check_movie_url
      uri    = URI.parse(@movieId) 
      params = CGI.parse(uri.query)
      @movie = Movie.find_or_initialize_by(movie_url: params["v"][0])
      if @movie.save
        @review = current_user.reviews.new(require_params)
        if @review.save
          flash.alert = "Reviwed Succesfuly"
          redirect_to reviews_path
        else
          render_error_message @review.errors.full_messages
        end
      else
        render_error_message @movie.errors.full_messages
      end
    else
      render_error_message "Please enter valid URL"
    end
  end

  def update
    if @review.update(require_params)
      redirect_to reviews_path
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to reviews_path
  end

  private

  def find_user
    @review = current_user.reviews.find(params[:id])
  end

  def require_params
    params.require(:review).permit(:rating, :description).merge!(movie_id: @movie.id)
  end

  def check_movie_url
    @movieId = (params[:review][:movie][:movie_url])
    pattern = Regexp.new(/(https?\:\/\/)?(www\.)?(youtube\.com)?(\/watch\?v=[A-Za-z0-9-_]{11})/)
    pattern.match?(@movieId)
  end

  def render_error_message(message)
    flash.alert = message
    @review = current_user.reviews.new
    render 'new'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieShare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <% flash.each do |name, msg| %>
      <%= msg %>
    <% end %>
  </body>
</html>

app/views/movies/index.html.erb
<h2 class="text-center pt-4">Youtube Movies</h2>
<div class= "container">
  <div class="row">
    <% @movies.each do |val| %>
      <div class="col-md-4">
        <div class="card">
          <iframe class="card-img-top" height="315" src="https://www.youtube.com/embed/<%=val.movie_url%>"></iframe>
          <div class="card-body">
            <h4 class="card-title"><%= val.title%></h4>
            <p class="card-text">Some example text some example text. John Doe is an architect and engineer</p>
            <%= link_to "See more", movie_path(val) %>
          </div>
        </div>
      </div>
    <% end %>  
  </div>
</div>

app/views/movies/show.html.erb
<div class="container">
  <iframe width="500" class="card-img-top" height="500" src="https://www.youtube.com/embed/<%=@movie.movie_url%>"></iframe>
  <table class="table table-striped">
    <thead>
      <tr>
        <th class="text-center">Description</th>
        <th class="text-center">Rating</th>
        <th class="text-center">Review By</th>
      </tr>
    </thead>
    <tbody>
      <% @movie.reviews.each do |post| %>
        <tr>
          <td class="text-center"><%=post.description%></td>
          <td class="text-center"><%=post.rating%></td>
          <td class="text-center"><%=post.user.email%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/reviews/edit.html.erb
<h2 class="text-center py-5"> Add Movie Review </h2>
<div class="container">
  <div class="shadow p-5">
    <%= form_for @review do |f| %>
      <div class="form-group">
        <%= f.label :description, for: "exampleInputPassword1" %>:
        <%= f.text_field :description , required: true, class: "form-control", id: "exampleInputPassword1", placeholder: "Description" %>
      </div>

      <div class="form-group">
        <%= f.label :rating, for: "exampleInputrating1" %>:
        <%= f.number_field :rating, min: 1, max: 5, required: true, class: "form-control", id: "exampleInputrating1" %>
      </div>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/reviews/index.html.erb
<h2 class="text-center pt-4">Customer Dashboard</h2>
<h6 class=" py-2 text-center"><%= link_to "Share Movie",  new_review_path %></h6>

<div class= "container">
  <div class="row">
    <% @reviews.each do |post| %>
      <div class= "col-md-4">
        <div class="card">
          <iframe class="card-img-top" height="315" src="https://www.youtube.com/embed/<%=post.movie.movie_url%>"></iframe>
          <div class="card-body">
            <h4 class="card-title"><%= post.movie.title%></h4>
            <p class="card-text">Description: <%= post.description %></p>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Rating: <%= post.rating %></li>
          </ul>
          <div class="card-body">  
            <%= link_to "Edit", edit_review_path(post) %>
            <%= link_to "Delete", review_path(post), :method => :delete %>
          </div>
        </div> 
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<h2 class="text-center py-5"> Add Movie Review </h2>
<div class="container">
  <div class="shadow p-5">
    <%= form_for @review do |f| %>
      <div class="form-group">
        <%= f.fields_for :movie do |a|%>
          <%= a.label :movie_url,  for: "exampleInputEmail1" %>
          <%= a.text_field :movie_url, required: true, class: "form-control", id: "exampleInputEmail1", placeholder: "Enter Movie url" %>
        <% end %>
      </div>
      <div class="form-group">
        <%= f.label :description, for: "exampleInputPassword1" %>:
        <%= f.text_field :description , required: true, class: "form-control", id: "exampleInputPassword1", placeholder: "Description" %>
      </div>
      <div class="form-group">
        <%= f.label :rating, for: "exampleInputrating1" %>:
        <%= f.number_field :rating, min: 1, max: 5, required: true, class: "form-control", id: "exampleInputrating1" %>
      </div>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active p-2">
        <a class="nav-link"><%= link_to "Home", root_path %></a>
      </li>
      <li class="nav-item p-2">
        <% if current_user.present? %>
          <a class="nav-link"><%= link_to "Dashboard", reviews_path %></a>
        <% end %>
      </li>  
      <li class="nav-item p-2 ">
        <% if current_user.present? %>
          <a class="nav-link"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></a>
        <% else %>
          <a class="nav-link"><%= link_to "Sign in", new_user_session_path %></a>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>